### ISSUE TITLE
Connections not closing - Causing Database to choke

### ISSUE THREAD

**Issue by mail4umar** [mfelici/dblink#2]
I am using verticalab to work with DBLINK. 

It seems like each SQL run opens a new connection. If i run too many commands, my database gives Fatal error and I am no longer to access my database. There are only two options:

1) restart my database
2) restart notebook kernel

I think it will be great if the connections are closed automatically.

**Comment by mfelici** [comment]
Thanks for the report!

Yes, this is a confirmed issue. Working on it...
