### ISSUE TITLE
Adding Unit Tests

### ISSUE THREAD

**Issue by oualib** [mfelici/dblink#4]
@mfelici, It would be nice if you could use Github action to set up a container with Vertica, another DB (like PostGres) and all the elements to install and run your function. We can find the engineers to help you to do it. If you build robust Unit Tests (different scenarios), we could probably push it to be part of the RPM. What do you think?

**Comment by roypaulin** [comment]
Good idea. I did something similar by building an image with dblink already installed but it would be awesome if it was already part of the RPM.

**Comment by mfelici** [comment]
I think this is a good idea. I already have "my own" non-containerized environment with several databases where I run my regression tests. If someone creates a container with Vertica, PostgreSQL, MySQL, etc... I will contribute with my test scripts.

**Comment by oualib** [comment]
Cool ! Can you give some rights to [sitingren](https://github.com/sitingren) , [afard](https://github.com/afard) AND [NerdLogic](https://github.com/NerdLogic). They can help here.

@roypaulin do you know how to set up a Github Action ?

**Comment by roypaulin** [comment]
> @roypaulin do you know how to set up a Github Action ?

I have done it once. I think I can remember. What should the github action do?

**Comment by oualib** [comment]
This is the process: 
1. install Vertica 
2. install DBLink UDx
3. install Postgres
4. create the different Connection ID needed by DBLINK
5. run a test script (it will be provided by Maurizio)
6. if the script fails it raises an error otherwise it tells us it is working
7. it closes and kills everything
8. we can then create a protected branch: the code can only be merged if the tests succeeded and one reviewer approves

**Comment by oualib** [comment]
It will be done in the Vertica repo: https://github.com/vertica/dblink/
