### ISSUE TITLE
Is it possible to connect using directly a DSN?

### ISSUE THREAD

**Issue by oualib** [mfelici/dblink#6]
It would be nice to have the same option as ODBCLoader. We can connect using directly a DSN string: 'DSN=some_odbc_dsn;<other connection parameters>', it would totally simplify the usage in VerticaPy. We will not have to create a CID file !

**Comment by mail4umar** [comment]
While we are at it. We might as well get option of getting rid of other odbc.ini file? 

We can default values for most of it nad just have aprameters like server name, database, port etc

**Comment by mfelici** [comment]
Connecting with the same syntax as the ODBC-Loader is an easy to implement feature. Will do.
Clearly whatever you write in the SELECT statement will be saved in the query_requests or visible in the "live sessions" if you have the proper access.

**Comment by oualib** [comment]
@mfelici aaah so it can create some security issues. We will clearly document the option to explain to the user the risk. Thanks for the information.

**Comment by oualib** [comment]
it will be done directly in the Vertica repo: https://github.com/vertica/dblink/issues/5
