### ISSUE TITLE
Two DBLINK calls not possible in a single querry

### ISSUE THREAD

**Issue by mail4umar** [mfelici/dblink#7]
I cannot seem to perform operations which require two calls of DBLINK either of the same database or different. I cannot do joins. Even UNION is not possible. Simple example:

```sql
SELECT * FROM ((SELECT DBLINK(USING PARAMETERS cid='pgdb', query='SELECT * FROM airline', rowset=500) OVER ())
UNION ALL
(SELECT DBLINK(USING PARAMETERS cid='pgdb', query='SELECT * FROM airline', rowset=500) OVER ())) AS airline;
```

I get an Error:
```
WARNING 2005:  Failure in UDx RPC call InvokeDestroy() in User Defined Object [dblink]: UDx side process has exited abnormally
ERROR 3399:  Failure in UDx RPC call InvokeProcessPartition(): Error calling processPartition() in User Defined Object [dblink] at [ldblink.cpp:353], error code: 400, message: Exception while processing partition: [DBLINK. Error executing the statement]
```

**Comment by mfelici** [comment]
No, this is not a BUG. Apart that UDTF have some restrictions (for example you cannot specify more than one user-defined transform function in the SELECT list) the idea behind DBLINK is to push SQL on the external database. So you push the JOIN or the UNION on the remote database using their engine.

You can JOIN multiple Vertica managed tables with a (single) result set retrieved via DBLINK possibly executing multiple joins in PostgreSQL or other databases.

If you need to use the Vertica engine to JOIN tables from multiple databases (apart any performance consideration about data movement) you have to use VFQ via External Tables.
